# general:
INPUT_FILES_FOLDER = '<INSERT PATH>'
OUTPUT_FILES_FOLDER = '<INSERT PATH>'
PROJECT_AUTO = '<INSERT PATH>'

# copy_recordings:
REC_DIR = '<INSERT PATH>'
INPUT_LOGFILE = INPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
OUTPUT_MATCHED_FILES = OUTPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
COPY_TARGERT_FOLDER = '<INSERT PATH>'
COPY_TARGERT_FOLDER2 = '<INSERT PATH>'

# create_koe_units:
INPUT_MATCHED_FILES = INPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
OUTPUT_UNITS_FILE = OUTPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
COLUMNS_NAMES = ['song', 'start_time_ms', 'end_time_ms', 'label_family', 'label_subfamily', 'label']
LABELS = ['TRILL', 'WHINE', 'COO', 'CS', 'GR', 'GWB', 'GWH', 'HW', 'HC', 'HTC', 'SQ', 'WB', 'GW', 'B', 'H']
COMB_HTC = 'HTC_HC_H'
COMB_GWB = 'GWB_GW'
COMB_GWH = 'GWH_HW'
SET_HTC_HC_H = {'HTC', 'HC', 'H'}
SET_GWB_GW = {'GWB', 'GW'}
SET_GWH_HW = {'GWH', 'HW'}

# Divide:
INPUT_UNITS_FILE = INPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
ROWS_LIMIT = 150
OUTPUT_DIV_UNITS = OUTPUT_FILES_FOLDER + '\\<INSERT CSV FILE NAME>'
INPUT_DIV_UNITS = PROJECT_AUTO + '\\<INSERT CSV FILE NAME>'
